title: "Ruihua Fan — Personal Website"
description: "Personal website of Edward (Ruihua) Fan, condensed matter theory."
email: "ruihua_fan@berkeley.edu"

# GitHub Pages settings
url: "https://ruihuafan.github.io"
baseurl: ""   # user site → keep empty

# Use kramdown for Markdown
markdown: kramdown

# kramdown:
  # math_engine: mathjax

# IMPORTANT: do NOT set a theme (minima, etc.), or it will override your CSS.
# Just leave `theme` unset, or explicitly null:
# theme: null

# Make all pages use the same custom layout with your inline CSS
defaults:
  - scope:
      path: ""        # all files
      type: "pages"   # only for pages (index.md, misc.md, etc.)
    values:
      layout: default
  - scope:
      path: ""
      type: "mknotes"   # collection name (plural)
    values:
      layout: mknote

collections:
  mknotes:
    output: true
    permalink: /notes/:path/


# Optional: nice URLs like /misc/ instead of /misc.html
# permalink: /:title/
permalink: pretty



