title: "Ruihua Fan"
email: "ruihua_fan@berkeley.edu"
description: >-
  Personal website of Ruihua Fan, condensed matter theorist.

url: "https://ruihuafan.github.io"
baseurl: ""   # user site â†’ leave empty

# Use the default GitHub Pages theme "minima"
theme: minima

# Pages that appear in the top navigation bar
header_pages:
  - index.md
  - misc.md

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

